### ISSUE TITLE
Add networked play

### ISSUE THREAD

**Issue by CurryKitten** [CurryKitten/CurryKitten-Sim#12]
Allow players to complete/fly with each other via the Internet.  I haven't started researching this as yet, but as there will be no dedicated servers available it's likely that one player will "hosts" with the others joining him... maybe.

**Comment by sasplayers** [comment]
As I'm a programmer myself in various Object Orientated Languages again networking would usually consist or between 4 and 8 players depending on network speeds, but it would be useful to learn from each other especially if VOIP or similar was implemented too.

**Comment by andhya** [comment]
guessing at 3 floats for position, 3 floats for orientation and 3 floats for velocity (to interpolate dropped frames), 288bits, round up to 512, 120fps max, 62kbps per user, at n up and n(n-1) down total for n users. @6 users that's 372kbps into the server and 1.9Mbps out of the server, per game... doesn't sound a huge amount to me? wonder if jack's work might be able to help out if having it hosted at a dedicated server makes it easier?

**Comment by CurryKitten** [comment]
Yes - something along those lines, although you forgot to allow for frame and UDP headers.  There's no issue in making code for this, it just needs more thought of implementation.  i.e how will people connect together, do we matchmake in a "room" and then go peer-to-peer, do we host on a dedicated server - how much would that be?  Unity, very inconveniently, actually does have a network play service that you can build into your code, but it's just depreciating this in favour of a new system that it hasn't released yet.... which is annoying.  I'll be doing some testing on this after a few more iterations of the sim.

**Comment by CurryKitten** [comment]
I've had a bit of a search around - given that Unity's own networking API is depreciated, but they haven't come up with a new one.  I can see Pun2 (https://www.photonengine.com/en-us/PUN) has a free license with 20 CCU which maybe a decent first experiment to see how things hold up.  Obviously, this can't scale up without giving them money (which I can't really do) so at some point we need an alternative - but I don't really want to write my own infrastructure just to match people together in order to play... .but that's several steps ahead - will test Pun out first and see how easy it is and how the sim performs

**Comment by CurryKitten** [comment]
Update - we are just about there.  I struggled for several weeks trying to get the remote players to update smoothly, this was mainly due to photons code being crap - so I implemented my own data exchange using their system for writing/reading streams over the network.

Changes include the main menu

![Screenshot 2020-05-05 at 18 11 30](https://user-images.githubusercontent.com/12443664/81399558-15921700-9123-11ea-8ca1-0aa54753f718.jpg)

From here you can put in your online name and join the lobby.  You can either join as the best (fastest server) or choose one.  The option to choose one turns out to be important as two computers in the same room decided that their best option was two different countries and then they couldn't see each other.

![Screenshot 2020-05-06 at 14 56 54](https://user-images.githubusercontent.com/12443664/81399673-50944a80-9123-11ea-8452-d4b8f1d14cea.jpg)

Once in the lobby, you can see any available rooms that you can join or create your own.

![Screenshot 2020-05-08 at 12 00 47](https://user-images.githubusercontent.com/12443664/81399853-b7b1ff00-9123-11ea-81a1-c2e39ea8d5e6.jpg)

If you create a room you are the owner and can start the game (should the owner leave, then the next person in the room becomes the owner)  If you are not the owner you have to wait for them to start.  If the game is already in progress you'll go straight into the Sim screen when you enter the room.

![Screenshot 2020-05-08 at 12 00 58](https://user-images.githubusercontent.com/12443664/81399949-ec25bb00-9123-11ea-9bd3-a8df2a84966f.jpg)

Each player (max of 4 as this was the recommended limit without a dedicated server) gets their own colour of pad and props so (hopefully) people can tell who is who

![Screenshot 2020-05-04 at 00 57 22](https://user-images.githubusercontent.com/12443664/81400036-2000e080-9124-11ea-9b93-67bc60796f1e.jpg)

When in game I've added options to have other quads show a trail (colour coordinated to them of course) and make bigger - both in order to see them easier

![Screenshot 2020-05-08 at 12 06 17](https://user-images.githubusercontent.com/12443664/81400208-7d952d00-9124-11ea-98ed-1c9dc94fcf44.jpg)

I'm not sure if the make bigger option will stay, there's issues with quads appearing to fall through the floor as the size is only visible from the local clients point of view (as well as the trails) which means on the ground the actual position of the normal sized quad would cause the extra large one to look like it was sunken.

Still having some thoughts about having the option for several overlays - one to tell you who was online and which colour they were, and another as a radar image to help track down where people had gone on the map.

**Comment by CurryKitten** [comment]
After some thought, a combination of a map overlay which tells you who's who based on a colour, and lets you find people in the game.

![Screenshot 2020-05-09 at 17 25 07](https://user-images.githubusercontent.com/12443664/81587167-8e58d380-93ae-11ea-86a8-31913800f740.jpg)

This is complete - although there's endless amounts of expansion that can be done in online, I'm going to roll this into the 0.47b release and see how the network copes (is 20CCU enough?) and then see what people need/want.
