### ISSUE TITLE
Can we support radios using trainer ports to USB dongles

### ISSUE THREAD

**Issue by CurryKitten** [CurryKitten/CurryKitten-Sim#14]
Had some feedback from users with varying degrees of success using trainer ports connected to USB dongles - essentially they work as PPM converters, but I'm not sure how they present themselves to the OS.  I've got a few old radios I may be able to test this with - so I'll try it out to see what's what

**Comment by howels** [comment]
If you are looking at a wide range of input devices then you may find that an input mapping layer like SDL2 provides some useful abstraction between raw devices and the axis get mapped to the game. I don't know what you're using currently but this is a common bugbear with the wide variety of modern input devices, and allowing for all of them in Unity.

**Comment by pkendall64** [comment]
I have a KSIM 4/8/All-in-one USB dongle that I have used with 0.3a of your Sim, with a RadioLink AT9 radio, and it worked fine. I just had to map the yaw to channel 6 in the radio. The Dongle is set to "G5-G7 Above" mode.
With the release of 0.4a, the dongle no longer works in any of the 4 switch modes. Basically the remap feature in the software does not detect stick movement on the channels. I did manage to get detect the throttle/yaw stick one time after a lot of mucking about, but then when I tried it again it didn't detect anything.
If there is any logging or testing you would like me to do, just let me know.
Great Sim BTW.

**Comment by CurryKitten** [comment]
Can you do one thing - if you are comfortably using regedit (I'm assuming you are on Windows) Rewired gets upset (apparantly) if you mess with the input dialog on the launcher.  if you delete the HKEY_CURRENT_USER\Software\CurryKitten entry (and everything below) from the registry, this will remove all the saved settings the sim have saved - this is just to check it still acts weirdly with the defaults settings.  

If it's still bad, that's one of those Chinese mad USB to trainer port dongles where you have switches to it'll work with Phoenix/RealFlight/etc isn't it?  I tihnk I have one about somewhere - so I'll do a test and see if I can figure out what's happening

**Comment by CurryKitten** [comment]
A little more on this - I've managed to find a 9-in-1 simulator dongle (helpfully enough you change the type of sim with software... which took some time to hunt down)  This appears to the system as a Saili Simulator, and stuck in it's default Phoenix mode didn't do anything, but as a G5.0 controller at least appeared as a joystick.

![IMG_7411](https://user-images.githubusercontent.com/12443664/72220990-58b1f400-354e-11ea-8f2d-59b9607183fc.jpg)

I did find - what looks like the same situation as @pkendall64 had with it picking up ch 6 for yaw, but with the other channels being ok.  The remapping was having some issues here.... to say the least.  There seems to be *something* that had an axis, or button set (albeit randomly) at a high level which was jumping in and grabbing the control before I could move the physical stick to set it.  Sometimes I managed 2 or 3 of the axis, and sometimes just 1.  After around 20 goes of trying this - all quite random looking in terms of how the program was reacting I did actually manage to get all the correct 4-axis sorted out.

This is more difficult to debug as this is a windows specific issue which is not my development platform (else it would be very easy)  It might be worth writing a small standalone app to display what the system thinks is the layout of the controller that's plugged in and the state of all the axis/switches/buttons.  The only potential spanner in that idea is that the system *thinks* that a Taranis has 32-axis and 256 buttons.. which is wrong on both counts, and makes displaying things very difficult.  We would hope though, that this phantom stick action which is taking place is on at least one of the available RC channels that exists on the radio.

**Comment by pkendall64** [comment]
My adapter is exactly as you say. It has a switch on the side for selecting the mode. The only one that works is the G5-G7 and above mode. I am on mac OSX Catalina, which I should have said earlier. I will have another go at it tonight after work. Thanks. If theres anything you need me to look at on the mac I can do that for you.

**Comment by CurryKitten** [comment]
@pkendall64 That was useful - thanks.  I didn't know those dongles worked at all on a Mac.  Now that mine was into G5 mode (via awful software that had to run in xp compatability mode on a win10 laptop) it was recognised on my Mac.

What I don't have here is the same radio as you, I was using the trainer port on a Taranis X9D and basically the remapping was falling over.  I was able to look at the state of all the axis/buttons/switches (albeit even if some of them don't physically exist) and what it told me was odd.  My moentary switch was flickering on and off, and if I actually used it, it made another button active.  The fact that I don't actually have any of these switches active in this model, or the fact that they themselves should be treated as axis is an interesting one, and the Rewired developer tells me that the hid info can be garbage on devices like this - perhaps this is the case.  I can fix this on my dev machine by ignoring button presses when prompting for stick remapping.  I'm not sure if this is going to help @pkendall64 case, but it's possible that something is being detected that should be and is blocking the remap, so I'll offer his a build to test with.

**Comment by CurryKitten** [comment]
Given the revamp of the calibration function in issue #33 I'm pretty confident this is now fixed... or will be with the release of 0.43a.  I've managed to fly with dongles that couldn't be previously made to work - so will close this off
