### ISSUE TITLE
X7 Taranis (first model) not detecting any stick other than Pitch

### ISSUE THREAD

**Issue by mbevilacqua** [CurryKitten/CurryKitten-Sim#26]
Testing FrSky Taranix QX7 on Mac (Mojave) connected directly through USB.
Sim detects the FRSKY TARANIS JOYSTICK but calibration only detects Pitch stick. Throttle, Yaw, Roll are not detected.
Also moving the throttle moves both the throttle and the yaw at the same time. If I throttle up in the controller the image in the sim shows the stick moving from the lower left corner to the top right corner.

**Comment by CurryKitten** [comment]
I'm running Mojave on my iMac and I have a QX7 that works fine.  Are you running the latest version of the sim, and did you try remapping your controls to get the sim to pick up your Throttle, Yaw and Roll.  Don't do the calibration before doing a remap (in most cases a calibration isn't necessary)

**Comment by CurryKitten** [comment]
Can you give me any more info on this @mbevilacqua or answer my questions, else I'll have to close it off

**Comment by CurryKitten** [comment]
No response, so closing issue

**Comment by mbevilacqua** [comment]
Hi just installed QuadSim-Mac-042a on another Mojave MackBook Pro and it has the exact same issues. Tried remap controls. Pitch is detected fine, then roll is not detected at all, then throttle is detected but the stick moved diagonally again from bottom left to top right, finally yaw is not detected at all. Controller works fine on other sims on this same MBP.

**Comment by CurryKitten** [comment]
@mbevilacqua  Curious as I'm running Mojave as well.  Could you send me your model settings from OpenTX companion and confirm what level of OpenTX you are running and then I can run it up on my radio just to make sure there's nothing odd in there.  Did you also try (in the 0.42a version) doing a restore of the default settings just to ensure there wasn't anything in your saved data screwing things up.  Will reopen the issue in the meantime

**Comment by mbevilacqua** [comment]
Restoring default settings fixed it for me! Thanks!

**Comment by CurryKitten** [comment]
Nice - thanks for letting me know.  I'll add the suggestion of resetting to default settings in the wiki as a first thing to do if some axis don't react.
