### ISSUE TITLE
Are secondary USB HID controllers grabbing the 1st joystick position ?

### ISSUE THREAD

**Issue by CurryKitten** [CurryKitten/CurryKitten-Sim#27]
This needs investigation, but based on some user feedback I found that whenever he was plugging his radio in, it would just show as "unknown" in the sim and then not respond.  Through some useful investigation from the user himself, he was able to determine that he had an extra USB HID controller he wasn't aware of.  When this was disabled, or removed then the sim would recognise the radios he tried and the sim would play fine.

My thoughts here are that the USB HID controller on the Windows machine was being recognised as a joystick, and the sim defaults to using the first joystick on the system.  Whilst I think we can resonably only expect 1 actual joystick, the potential use of HID controllers for other sorts of devices may mean we have to rethink our joystick allocation.

A quick test of some code showed me that when I plugged a second joystick into my system, I received an OnControllerChanged event, but that the joystick count was still only 1.  I also noted that if I removed the 1st radio I'd connected, and left the second plugged in, then the existing joystick would get reallocated to joystick 0 and so the sim would sit there saying no joystick was connected.

This second part is probably a corner case that doesn't need any work, but I will allocate some time to investigate how to detect multiple joysticks with the intention of giving the user a choice of which to use.

**Comment by marksu78** [comment]
I have similar problem. I have a 3D Connexion Space Navigator (thingy for navigating in 3D modelling environment) and Windows sees that as a game controller. 

So now windows has two USB game controllers but i'm not able to select the controllerI want to use in the simulator. All other simulators give me the choice of what Joystick I want to use so i have been able to play those.

So yes it would be great to have choice of what game controller to use

**Comment by CurryKitten** [comment]
Thanks for letting me know about this @marksu78 an oversight on my part.  I thought a joystick would be a joystick and thought is normal that on a PC you'd usually only have one.  But windows seems to have its own idea.  I have to dive back in the whole input section when I add switches as functions (like reset) so I expect I'll attempt to implement being able to choose a joystick to use at the same time.

**Comment by CurryKitten** [comment]
Started working on this.  Interestingly with 2 controllers available, Rewired only allocates the first one to the player, and the second is an unassigned controller.  When the first controller is disconnected, the second controller doesn't jump in as available, but has to manually be assigned.

My initial code on this detects that a one or more additional joystick are available and puts text out to display this as a button.

![Screenshot 2020-02-04 at 00 21 16](https://user-images.githubusercontent.com/12443664/73702348-6e957d80-46e4-11ea-8abe-c257f1c4c305.jpg)

The function on clicking on this button will be to then allow an alternative joystick to be chosen.  I'm not sure what approach will be taken for this yet - either a drop-down, or cycling through the options.

What I did do is code in reassigning of joysticks, so if joystick 1 is active and joystick 2 exists, if joystick 1 is removed, then joystick 2 becomes active and is allocated to the player.

**Comment by CurryKitten** [comment]
@marksu78 I *think* I have this done.  I can switch between 2 radios I've plugged in and got it to remember my choice etc.  Is it possible you could try a build out and see if it works for you?  Ping me a mail at currykittensim@gmail.com if you can.

**Comment by CurryKitten** [comment]
Pretty confident I've fixed this now - looking at the previous screen grab, clicking on the (alternate joystick detected) text will open up a drop down with all the detected joysticks available

![Screenshot 2020-02-07 at 15 20 13](https://user-images.githubusercontent.com/12443664/74044825-a0982f80-49c3-11ea-8cd1-d8681aea4250.jpg)

Once you choose one of these from the menu, it becomes the preferred joystick and so if multiple joysticks are detected, and your preferred joystick is one of them, the game will automatically allocate you your preferred one to use... although if it's then unplugged it will use the one that's leftover.

This code will go into the 0.43a release
