### ISSUE TITLE
Add some bridges and interiors

### ISSUE THREAD

**Issue by pashky** [CurryKitten/CurryKitten-Sim#41]
Hi Wayne,

Thank you so much for the sim, finally I can fly on my elderly MBP, and no need to kick off my son off steam account too. 

Is there chance you could add some bridge or arch-like constructions onto the map, and perhaps something like unfinished buildings? No fancy details, just some pillars and slabs and empty windows would do. Kind of like bando city map on Liftoff if you've seen it? It would greatly help to practice some vertical acro stuff and precise altitude control.

**Comment by CurryKitten** [comment]
Yes - one of the things in plan is to have a building site-type area with unfinished buildings and some cranes.

I've had a few calls for bridges, so I'll look to see if there's a model and the right sort of space to fit this in somewhere.

**Comment by CurryKitten** [comment]
Nathan (he who has been making some models) came up with some components for me to build something 

![Screenshot 2020-04-14 at 14 00 28](https://user-images.githubusercontent.com/12443664/79852309-68976a80-83be-11ea-9ba7-175e5f2427a4.jpg)

This looks a bit odd at first, but the idea of having this as a contruction kit is that I can add colliders to each individual element easily and then use them as prefabs to build something.  These will be use for making a part-build office block - as Nathan's Fusion360 screenshot shows.

![Screenshot 2020-04-21 at 10 54 33](https://user-images.githubusercontent.com/12443664/79852516-ac8a6f80-83be-11ea-8d0e-abf4186ac51d.jpg)

**Comment by CurryKitten** [comment]
I used the assets to construct a part-constructed building that you can fly into and through.  It works quite well, but does feel tight - despite being 3m in height.

![Screenshot 2020-04-23 at 16 44 47](https://user-images.githubusercontent.com/12443664/80159540-28eda000-85c3-11ea-9822-dab9c573271b.jpg)

I've got some bridge models, but I'm having trouble shoe-horning them into the current setup.  I'll need the landscape to work for a bridge before we add it, but it's still on the to-do list

**Comment by pashky** [comment]
That's great! Can't wait to try it out.

**Comment by CurryKitten** [comment]
Someone in the YouTube comments suggested doing a walkway between 2 buildings as a bridge sort of thing.  

![Screenshot 2020-04-26 at 01 07 13](https://user-images.githubusercontent.com/12443664/80293784-5caefe00-875a-11ea-97be-71025c58ad3d.jpg)

While not a perfect blend (it's another building turned on it's side and stuffed through the other 2) it serves the purpose, and you can happily try flipping around it and stuff

If I don't manage to put a more aesthetically pleasing bridge in for the next release, then this is staying

**Comment by CurryKitten** [comment]
Bridge is in 0.56b in the valley level, so closing this off
