### ISSUE TITLE
Possible issue with the DJI FPV radio

### ISSUE THREAD

**Issue by 5zero7rc** [CurryKitten/CurryKitten-Sim#45]
Myself and a few others have an issue with using the DJI FPV radio with flight simulators including this one where the edges of the sticks "wrap" around.  I assume it is a DJI issue but I was also wondering if it could be detected by the simulator and corrected some how.

Anyway, not a huge deal but here is a video showing the issue in more detail.
[https://youtu.be/fep7FFFi3vs](url)

**Comment by CurryKitten** [comment]
That video was super-helpful... thanks.  It looks a bit like a previous problem I was getting many revisions ago.  If so, it's not possible to detect and work around as the joystick signal that comes form the radio literally goes from max to min.  If the signal was simply going out of bounds then a simple calibration would have fixed it.  If I can get hold of  DJI controller I can try and get some raw data out of it and build a profile that might fix it but that pretty much depends on someone at DJI being drunk/high enough to ship me one.  Worth a try though

**Comment by 5zero7rc** [comment]
Thanks for taking a look.  I was able to make it much better by calibrating the sticks in the DJI goggles.  Not perfect, but better.  Hopefully you will find yourself with a set of DJI FPV gear eventually.  Loving the sim so far!
