### ISSUE TITLE
CopterX USB Transmitter- Yaw Not Detected- User Error Disregard

### ISSUE THREAD

**Issue by MKme** [CurryKitten/CurryKitten-Sim#48]
I was hoping to use my old Copter-X USB transmitter (was from on old heli sim) but the yaw axis is not detected in your SIM.  In the USB control properties yaw shows up as rudder no issue. Perhaps if you expanded to look at more channels or?  Would love to give this a go

![Rudder in this display but not detected in SIM](https://user-images.githubusercontent.com/13653062/80262398-4ec68380-865b-11ea-9d3a-f6b598846c24.PNG)
![IMG_2976](https://user-images.githubusercontent.com/13653062/80262436-669e0780-865b-11ea-9ac3-4917ce7abc6d.JPG)

**Comment by MKme** [comment]
Disregard- I have no idea what changed but I killed the USB, rebooted, reinstalled and retired and it gets picked up now.  Yay!

**Comment by CurryKitten** [comment]
Yay - I like the self-resolving issues :D  Just to clarify though, although I only show the first 8 axis on the debug screen, the Sim gets the axis info from the USB HID info and scans all those axis for movement during the calibration.  The rule of thumb is usually that the first 8 axis are RC channels in use, but having just tested a little USB dongle for sims that has a built in D8 receiver, it mapped RC channel 1 to axis 0, 2 to 1, but then 3 to 10, 4 to 11 and then 5-8 to axis 18-21 so I'll have to rethink this debug page at some point.
