### ISSUE TITLE
Unable to knock beachball into ocean

### ISSUE THREAD

**Issue by morganwdavis** [CurryKitten/CurryKitten-Sim#59]
This is a serious bug.  I'm surprised it has not been reported yet.

While attempting to repro, I noticed the beachball should have the LDO logo on it. Please consider this so we can feel better about giving it a mighty thump at 230mph.

**Comment by CurryKitten** [comment]
I spent all that time making sure it bounced off of the limits of the game area so you didn't keep losing the balls!  The ball will probably change in some way once gamefication happens

**Comment by morganwdavis** [comment]
I was being cheeky, of course. Although I think the LDO homage logo -- or configurable ball themes -- is a nifty idea.  Sell beachball sponsorships! BTW, this is the first sim I can fly on my laptop that doesn't spin the fans, which is saying something. Great work on this, Wayne.
