### ISSUE TITLE
Try a different racing style...

### ISSUE THREAD

**Issue by graywoulf** [CurryKitten/CurryKitten-Sim#61]
FPV racing for a beginner is way too complicated and needs to be made a lot easier. May I propose something like a pylon course similar to those used in airplane racing. I have been flying sims that have trees that are set a ways from each other and fly around them in a smoother pattern which allows me to get used to making sharp turns without having to be less than half a meter from the ground to make the turn. The gates that are used are just too low and close together for my skill level. I also enjoy flying through the mountains as well as diving the mountains so thanks for those.

You have created a great FPV simulator and I feel that you are going to be very competitive with Velocidrone and Liftoff someday soon. Thanks and take care.

**Comment by CurryKitten** [comment]
I'm personally not a massive fan of racing through gates at the best of time, but I certainly take your points about the gates being tricky for beginners - certainly keeping that close to the ground to make people come unstuck quite often.  In #54 I've opened up the issue to redo the racing aspect of the sim.  Initially, I wanted to make this more of an adventure/explore circuit than a race - so much larger courses with "gates" in interesting places.  But I like the pylon idea as an easier alternative to gates - so I'll close this and add those ideas to it when I come to it.  Thanks

**Comment by graywoulf** [comment]
I really like that you intended this sim to be an adventure/explore type sim. I just assumed that having the gates was due to the popularity of FPV racing. I live near the Blue Ridge Mountains in NC and want to fly my quad in the rolling hills and open fields mostly. I have no real interest in racing but I like the idea of pylon racing like the airplanes do. But most of my flying skills have been flying around and through the trees in other sims. One of my favorite sim scenarios is in the Liftoff sim where I can fly over and around "The Green" which is a golf course. I don't care that it is a golf course but I like the diverse terrain and placement of trees to fly over and around. A couple of ponds and gazebos to fly around and through is interesting. As far as I am concerned, your sim provides that terrain. And if you want to add more trees... go for it.  Your sim with the beach balls, cars to chase and plane to chase is outstanding and way more fun than the rest.  👍👍

Thanks for listening to your "fans" and considering our ideas. I'm still looking forward to the next version of "CurryKitten" simulator and hope it is out soon.
