### ISSUE TITLE
Add planes to the online multiplayer game

### ISSUE THREAD

**Issue by CurryKitten** [CurryKitten/CurryKitten-Sim#63]
As per the subject, currently, planes aren't an option in multiplayer.  I also need to decide if I'm going to give some control over the room owner about if the other players joining are allowed to use planes.  This is something that I'll need to do in some way as there maybe other rules that apply in later games such as max power allowed, if the host should decide on the gravity etc

**Comment by T-pix425** [comment]
No worries... I NEVER want to even HEAR your name again...much less SEE YOUR FACE!! I'm not coming around and Daniel is going to either cut this shit out or LET ME GO COMPLETELY!! His choice..but he doesn't get to have BOTH!!

**Comment by CurryKitten** [comment]
@T-pix425 erm.... and indeed huh ?

**Comment by CurryKitten** [comment]
Ok, decided the first stage is to sort out the UI and room rules before we even think about getting the plane in the room.

So when a user creates a room we'll need a drop down for the types of model which will be "Open" or perhaps "Any" the default is to allow anyone to fly anything, and then under those options we'll have "planes only" and "quads only".

This needs to translate into the room listings to show anyone wishing to join a room what's allowed (or not) and finally when joining a room, if it's open, we need to give the user a choice of joining in a plane or a quad.

**Comment by CurryKitten** [comment]
Ok, done - will push this out in the 0.50b release
