### ISSUE TITLE
Joystick detection issue

### ISSUE THREAD

**Issue by 3djc** [CurryKitten/CurryKitten-Sim#75]
I have a  HOTA joystick permanently connected for FS2020, and plug OpenTX radio when needed. Windows sees the radio just fine, but the sim doesn't show the alternate joystick choice

Windows joypad config:
![image](https://user-images.githubusercontent.com/5167938/103408420-b32ed080-4b62-11eb-9ed8-7a42cd3bf514.png)

In game
![image](https://user-images.githubusercontent.com/5167938/103408447-ce014500-4b62-11eb-889d-2e0ab61bea5c.png)

**Comment by CurryKitten** [comment]
Since this is an OpenTX based radio, have you checked Windows hasn't updated you to the dreaded Better-USB driver?

**Comment by CurryKitten** [comment]
Oops, apologies @3djc I didn't know you were an active OpenTX developer, so I would guess that you know if you've got the right driver installed or not :D

I can't seem to replicate the problem you have (although I don't have the same hardware exactly)  The actual code just basis this dropdown on the question of how many joysticks are available and has a callback to update this if the number of joysticks change.  I have had the situation in the past where my Taranis radios for some reason don't appear dynamically and I've had to quit out of the program and restart (which makes it happy) but typically in trying to track this down, it then works 100% of the time.

But please let me know if you are still experiencing this and if there's any difference between starting up with the radio plugged in vs plugging in after the sim has already started

**Comment by CurryKitten** [comment]
This has sat around for a month with no updates, so I assume all is good.  If not, @3djc please reopen and we'll take another look.
