### ISSUE TITLE
Where to find / buy

### ISSUE THREAD

**Issue by eXpire163** [CurryKitten/CurryKitten-Sim#90]
Please add a link to Readme.md and Wiki to where to find/buy the game.

I found till now only the steam link via google
(https://store.steampowered.com/app/1331330/CurryKitten_FPV_Simulator/)

**Comment by CurryKitten** [comment]
Steam link added to the readme.  I'm not going to further add the releases link to the readme though.  Aside from the fact that I add direct download links to every YouTube video that accompanies a release, if you make it to github I'm hoping that you can find the releases link as well
