### ISSUE TITLE
Loading City Level causes all graphical output to freeze

### ISSUE THREAD

**Issue by howels** [CurryKitten/CurryKitten-Sim#93]
I can fly fine in the "original" level but when loading the "city" level all graphics freeze and I cannot even bring up the menu. 

I can see a static shot of the take-off spot in the city and hear motor noise when raising the throttle but my view never changes and I cannot open the menu using ESC any longer.  

Log attached. I see lots of errors like this:

```

The referenced script (CScape.CScapeLODManager) on this Behaviour is missing!
 
(Filename:  Line: 195)

The referenced script (CSMaterialTools) on this Behaviour is missing!
 
(Filename:  Line: 195)

The referenced script (CScape.TextureArrayTools) on this Behaviour is missing!
 
(Filename:  Line: 195)

The referenced script (DetailMaterialTools) on this Behaviour is missing!
 
(Filename:  Line: 195)

The referenced script on this Behaviour (Game Object 'CScape City') is missing!
 
(Filename:  Line: 294)

```

[vulkan-log.log](https://github.com/CurryKitten/CurryKitten-Sim/files/6393537/vulkan-log.log)

**Comment by howels** [comment]
I tried OpenGL to see if that was the issue - same exact problem. Running Ubuntu 20.04 LTS with Nvidia drivers.

**Comment by CurryKitten** [comment]
Hi @howels Thanks for providing the log.  So the stuff along the lines of -

`The referenced script (CSMaterialTools) on this Behaviour is missing!`

Are not a particular issue.  It refers to a script that's not found, but does so on objects that aren't in use as well.  It's a slight lack of tify up on the Cscape asset... along with all the messages of -

```
A scripted object (probably DetailMaterialTools?) has a different serialization layout when loading. (Read 32 bytes but expected 80 bytes)
Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?
```

Just so I know what's new here, do you get all the messages along the lines of

```
Fallback handler could not load library /home/stephen/Downloads/CK-FPV-Sim-Linux64-055b/CK-FPV-Sim-Linux64-055b_Data/Mono/libudev.so.0.so
Fallback handler could not load library /home/stephen/Downloads/CK-FPV-Sim-Linux64-055b/CK-FPV-Sim-Linux64-055b_Data/Mono/libudev.so.0
```

On the regular level as well?  Also, do you get the messages about unsupported shaders on both Vulkan and OpenGL?

```
WARNING: Shader Unsupported: 'CScape/Balcony' - All passes removed
WARNING: Shader Unsupported: 'NordLakeLite/NordLakeRiver' - All passes removed
WARNING: Shader Unsupported: 'CScape/CSRooftops' - All passes removed
```

The black screen without anything else going on is a bit of a weird one, even if the shaders aren't compatible, we should still be drawing the regular menu up there (a bit like how iOS right now draws the buildings as black rectangles)

**Comment by howels** [comment]
Log from original level included. Same messages about Fallback handler are present - I think Unity is missing some libraries but udev should only affect input and that's working fine.
I see a single static frame of the city, not a black screen nothing moves at all. I can't then exit to the menu.

In this log I load straight into the original level and fly for a few seconds then quit. So the differences between the two logs should highlight what's going on with the city level.
[vulkan-original-level-055b.log](https://github.com/CurryKitten/CurryKitten-Sim/files/6397601/vulkan-original-level-055b.log)

**Comment by CurryKitten** [comment]
Hi @howels I'm struggling to find the error here - I'm thinking you ight be somehow hitting a state in which everything is inbetween - so to speak.  So it somehow is sitting there but before any input, or gui or anything else (it's all guesswork though) My attempts to recreate this on my Linux VM has failed and it annoyingly keep running perfectly. 

In order to try and detangle the city from the sim at least see if we can remove one from the equation, can you try this city demo scene.  It should just show a city and allow you to walk around it FPS style (mouse look and AWSD) you will have to kill the process to exit though.  If that works then it's more likely some issue in the sim.  Can you let me know what you have set in the preferences screen. as well.  Download here https://drive.google.com/file/d/1fQ23Uy5W9j1plI1YA5ytNMt2Z2r140B5/view?usp=sharing

**Comment by howels** [comment]
> Hi @howels I'm struggling to find the error here - I'm thinking you ight be somehow hitting a state in which everything is inbetween - so to speak. So it somehow is sitting there but before any input, or gui or anything else (it's all guesswork though) My attempts to recreate this on my Linux VM has failed and it annoyingly keep running perfectly.
> 
> In order to try and detangle the city from the sim at least see if we can remove one from the equation, can you try this city demo scene. It should just show a city and allow you to walk around it FPS style (mouse look and AWSD) you will have to kill the process to exit though. If that works then it's more likely some issue in the sim. Can you let me know what you have set in the preferences screen. as well. Download here https://drive.google.com/file/d/1fQ23Uy5W9j1plI1YA5ytNMt2Z2r140B5/view?usp=sharing

requested access to the file.

**Comment by howels** [comment]
Working fine with this version, log attached @CurryKitten 

I am able to load, select appropriate resolution and enter the city whereupon I see a city with limited lighting but all textures rendered properly and I am able to move around.
[city-test.log](https://github.com/CurryKitten/CurryKitten-Sim/files/6475466/city-test.log)

**Comment by CurryKitten** [comment]
Hi @howels I've partially recreated this (I think) by using the option to start sim in game.  Did you use this option (it's something I'm actually intending to remove at the next release)

It does seem like I didn't take into account moving between levels when having this option enabled, so I do get a still picture of the city when moving level and hitting escape does nothing o pressing the mouse button for the quick menu, and I can't fly.  I do get a quad noise with my throttle though.  What I can still do is hit space to bring up the scenarios menu, and once escaping out of that everything is back to normal.  i can also do a few things like move the camera angle up/down.

Does any of that reflect your situation?

**Comment by howels** [comment]
Aha! Yes, I was using the option to start in-game so I can jump in and fly around for a few minutes easily without the menus. I will try with this disabled later today.
I'll try the scenarios menu, didn't know that key binding.

**Comment by howels** [comment]
@CurryKitten you're exactly right - the space bar worked and allowed me to bring up the menu, re-launch the level and fly around the city. Now I now.

**Comment by CurryKitten** [comment]
Closing off as we have a workaround.  The option to start in-game will disappear in the next release.  This is due to me a) forgetting it was there and then hitting two issues recently (including this one) and b) it making slightly less sense now.  Previously there was nothing else going on in that pause menu aside from the joystick setup
