### ISSUE TITLE
OSM as city level to fly anywhere around the world

### ISSUE THREAD

**Issue by ghost** [CurryKitten/CurryKitten-Sim#94]
Hi,

Flying in any city we want in the world :
1) with a preloaded Map (by selecting a street address as the center then a range to limit the size  of the map to preload)
Or
2) on line

By using OSM (OpenStreetMap) data to "easily" give you the way to use the available data.

It will then allow us to fly anywhere in the world for visit or in our city (just for fun to share this place as a game place)

Thank you.

**Comment by CurryKitten** [comment]
Aside from being way out of the scope of what I'm trying to do here, OSM doesn't give any height map information.  All you get is a general idea of "this area is a forest, this is a road, this is a building" etc  You can't make a very interesting map with very rough 2 dimensional data points.
